"""add user_id index

Revision ID: 35e1e49b74b8
Revises: 4721c4ef036b
Create Date: 2026-03-13 12:19:59.506994

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35e1e49b74b8"
down_revision: str | None = "4721c4ef036b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_logs_user_id"), "logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logs_user_id"), table_name="logs")
    # ### end Alembic commands ###
